doctrine:
    dbal:
        
        host: 'localhost'
        port: '%database.port%'
        dbname: 'novel'
        user: 'root'
        password: 'root'
        charset: UTF8
        options:
            1002: "SET NAMES 'UTF8'"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true